config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

resources :appointments
resources :customers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationController
    belongs_to :customer
    has_many :customers, through: :mechanics
end

app/models/customer.rb
class Customer < ApplicationController
    has_many :appointments
    has_many :mechanics, through: appointments
end

app/models/mechanic.rb
class Mechanic < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    def new
        @appointment = Appointment.new 
    end 

    
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
    end

    def new
        @customer = Customer.new
    end

    def create
        @customer = Customer.create(customer_params)
        redirect_to customer_path(@customer)
    end

    def destroy
        @customer = Customer.find(params[:id])
        @customer.destroy
        redirect_to index
    end

    private
    def customer_params
        params.require(:customer).permit(:name, :username, :car_make, :car_model, :car_year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<h2>Appointment</h2>

<%= form_for [@appointment.customer, @appointment] do |f| %>
    <%= f.label :date %>
    <%= f.text_field :date %>
    <br>
    <%= f.label :customer %>I think customer id needs to go here
    <%= f.text_field :customer %>
    <br>
    <%= f.label :notes %>
    <%= f.text_area :notes %>
    <br>
    <%= f.label :mechanic %>
    <%= f.text_field :mechanic %>
    <br>
    <%= f.submit "Make Appointment" %>
<% end %>

app/views/appointments/edit.html.erb
<h2>Edit Review</h2>

<%= render 'form' %>

app/views/appointments/index.html.erb
<h3>Appointments</h3>

<% @appointments.each do |appointment| %>
<% end %>

app/views/appointments/new.html.erb
<h1>Appointments</h1>

<%= render 'form' %>

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
    <%= f.label :car_make %>
    <%= f.text_field :car_make %>
    <%= f.label :car_model %>
    <%= f.text_field :car_model %>
    <%= f.label :car_year %>
    <%= f.text_field :car_year %>
    <%= f.submit %>
<% end %>

app/views/customers/edit.html.erb
<h2> Edit your car information </h2>

<%= render 'form' %>

app/views/customers/new.html.erb
<h2>Add a new car </h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DriveIn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/customers.html.erb
<%= @customer.username %>
<%= link_to "Book a new appointment", new_customer_path(@customer) %> | <%= link_to "View current appointments", customer_path(@customer) %>

<%= yield %>